platform :ios, '8.0'
def common_pods
    pod 'AFNetworking', '~> 3.1.0'
    pod 'Masonry', '~> 1.0.2’
    pod 'SDWebImage', '~> 4.3.3'
    pod 'HUPhotoBrowser', '~> 1.2.3'
    pod 'YYModel', '~> 1.0.4'
    pod 'MJRefresh', '~> 3.1.15.1'
end
target 'TestMulTargets' do
    common_pods
end
target 'TargetB' do
    common_pods
end
